---
- hosts: all
  become: yes
  tasks:
    - name: Add custom lines to .bashrc
      blockinfile:
        path: /home/ubuntu/.bashrc
        block: |
          alias l='ls -lrth'
          alias c=clear
          alias vi=vim
          PS1='\[\033[01;32m\]`pwd`>\033[00m\]'
        marker: "# {mark} ANSIBLE MANAGED BLOCK"
        insertafter: EOF
        create: yes
